version: "3.8"

services:
#//////////////////////////////////////////////////////////////////////////////
# Nginx
#//////////////////////////////////////////////////////////////////////////////
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
    image: nginx
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - inception
    ports:
      - "443:443"
    restart: always

#//////////////////////////////////////////////////////////////////////////////
# MariaDB
#//////////////////////////////////////////////////////////////////////////////
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb/
      args:
        DB_USER: ${DB_USER}
        DB_USER_PASSWORD: ${DB_USER_PASSWORD}
        DB_ROOT: ${DB_ROOT}
        DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    env_file:
      - .env
    image: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always

#//////////////////////////////////////////////////////////////////////////////
# WordPress
#//////////////////////////////////////////////////////////////////////////////
  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
    env_file:
      - .env
    image: wordpress
    volumes:
      - wordpress:/var/www/html/
    networks:
      - inception
    restart: always

#//////////////////////////////////////////////////////////////////////////////
# Networks
#//////////////////////////////////////////////////////////////////////////////
networks:
  inception:
    name: inception
    driver: bridge

#//////////////////////////////////////////////////////////////////////////////
# Volumes
#//////////////////////////////////////////////////////////////////////////////
volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ngennaro/data/mariadb
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ngennaro/data/wordpress